<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<!--
  Sternprodukt-Atlas · Basisstil (themenneutral)
  Geometrie : Punkt
  Felder    : branche (Text: eisen|buntmetall|aluminium|maschinen|fahrzeuge|schiffe|chemie|raffinerie|elektro|textil|nahrung|papier|zement)
              groesse (Zahl in mm, 2.2 klein · 3.4 mittel · 4.8 groß; NULL → 3.4) · name (Text)
  Verhüttende Industrie (eisen, buntmetall, aluminium) trägt den Tiegel — braucht basis/svg/tiegel.svg
  im SVG-Pfad. Alle übrigen Branchen: Kreis mit Kennbuchstabe (FontMarker, Noto Sans Mono).
  Farben aus atlas/farben.js; keine neuen Werte erfinden.
-->
<qgis version="3.28" styleCategories="Symbology">
<renderer-v2 type="categorizedSymbol" attr="branche" forceraster="0" enableorderby="0" symbollevels="1" referencescale="-1">
<categories>
<category render="true" value="eisen" symbol="0" label="Eisen"/>
<category render="true" value="buntmetall" symbol="1" label="Buntmetall"/>
<category render="true" value="aluminium" symbol="2" label="Aluminium"/>
<category render="true" value="maschinen" symbol="3" label="Maschinen"/>
<category render="true" value="fahrzeuge" symbol="4" label="Fahrzeuge"/>
<category render="true" value="schiffe" symbol="5" label="Schiffe"/>
<category render="true" value="chemie" symbol="6" label="Chemie"/>
<category render="true" value="raffinerie" symbol="7" label="Raffinerie"/>
<category render="true" value="elektro" symbol="8" label="Elektro"/>
<category render="true" value="textil" symbol="9" label="Textil"/>
<category render="true" value="nahrung" symbol="10" label="Nahrung"/>
<category render="true" value="papier" symbol="11" label="Papier"/>
<category render="true" value="zement" symbol="12" label="Zement"/>
</categories>
<symbols>
<symbol type="marker" name="0" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SvgMarker" enabled="1" locked="0" pass="0"><prop k="name" v="tiegel.svg"/><prop k="color" v="67,68,98,255"/><prop k="outline_color" v="67,68,98,255"/><prop k="outline_width" v="0.3"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="angle" v="0"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 1.35"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="1" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SvgMarker" enabled="1" locked="0" pass="0"><prop k="name" v="tiegel.svg"/><prop k="color" v="148,112,47,255"/><prop k="outline_color" v="148,112,47,255"/><prop k="outline_width" v="0.3"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="angle" v="0"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 1.35"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="2" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SvgMarker" enabled="1" locked="0" pass="0"><prop k="name" v="tiegel.svg"/><prop k="color" v="139,129,115,255"/><prop k="outline_color" v="139,129,115,255"/><prop k="outline_width" v="0.3"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="angle" v="0"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 1.35"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="3" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="67,68,98,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="M"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="4" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="203,90,42,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="F"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="5" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="47,111,116,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="S"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="6" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="90,58,82,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="C"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="7" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="90,58,82,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="R"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="8" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="34,84,90,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="E"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="9" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="185,142,63,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="T"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="10" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="111,117,56,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="N"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="11" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="84,89,42,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="P"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
<symbol type="marker" name="12" alpha="1" clip_to_extent="1" force_rhr="0"><layer class="SimpleMarker" enabled="1" locked="0" pass="0"><prop k="name" v="circle"/><prop k="color" v="139,129,115,255"/><prop k="outline_color" v="42,35,28,255"/><prop k="outline_style" v="solid"/><prop k="outline_width" v="0.13"/><prop k="outline_width_unit" v="MM"/><prop k="size" v="3.4"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4)"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer><layer class="FontMarker" enabled="1" locked="0" pass="1"><prop k="font" v="Noto Sans Mono"/><prop k="chr" v="Z"/><prop k="color" v="253,253,253,255"/><prop k="size" v="2.0"/><prop k="size_unit" v="MM"/><prop k="offset" v="0,0"/><prop k="angle" v="0"/><data_defined_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="properties" type="Map"><Option name="size" type="Map"><Option name="active" type="bool" value="true"/><Option name="expression" type="QString" value="coalesce(&quot;groesse&quot;, 3.4) * 0.58"/><Option name="type" type="int" value="3"/></Option></Option><Option name="type" type="QString" value="collection"/></Option></data_defined_properties></layer></symbol>
</symbols></renderer-v2>
<layerGeometryType>0</layerGeometryType>
</qgis>
